sudo: required

services:
- docker

arch:
    packages:
    - python
    - python-pip
    script:
    - make travis

script:
- "curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash"

notifications:
    email:
        on_success: change
        on_failure: change
