language: python
matrix:
    include:
        - python: 3.7
          dist: xenial

install:
    - pip install pycodestyle pydocstyle pyxdg

script:
    - make

notifications:
    email:
        on_success: change
        on_failure: change
