#!/bin/bash
trap '' 2
function _section() {
    cat PKGBUILD | grep "^$1=" | cut -d "=" -f 2 | sed "s/\"//g;s/'//g" | head -n 1
}
cd {DIRECTORY}
makepkg {MAKEPKG}
exit_code=$?
CUR_VERSION="{VERSION}"
if [ ! -z "$CUR_VERSION" ]; then
    PKG_VERSION=$(_section "pkgver")
    PKG_REL=$(_section "pkgrel")
    if [[ "$PKG_VERSION-$PKG_REL" == "$CUR_VERSION" ]]; then
        echo " => no change to version ($CUR_VERSION)"
        exit 1
    else
        exit 0
    fi
fi
if [ $exit_code -eq 0 ]; then
    if [ $(ls | grep "\.pkg\.tar\.xz$" | wc -l) -gt 0 ]; then
        for d in $(echo '{}'); do
            {SUDO} cp *.pkg.tar.xz $d
        done
    fi
fi
exit $exit_code
