#!/bin/bash
trap '' 2
cd {DIRECTORY}
makepkg {MAKEPKG}
exit_code=$?
if [ $(ls *.pkg.tar.xz | wc -l) -gt 0 ]; then
    for d in $(echo '{}'); do
        {SUDO} cp *.pkg.tar.xz $d
    done
fi
exit $exit_code
