.TH SEE "1" "<Month Year>" "naaman.conf" "User Commands"
.SH NAME
naaman.conf
.SH SYNOPSIS
$XDG_CONFIG_HOME/naaman.conf
.SH DESCRIPTION
naaman configuration file key information
.SS "options:"
.TP
BUILDS
see naaman '\-\-builds' for information
.TP
IGNORE
see naaman '\-\-ignore' for information
.TP
IGNORE_FOR
see naaman '\-\-ignore-for' for information
.TP
MAKEPKG
makepkg options. these entries are passed directly to makepkg.
This option may be specified multiple times.
.TP
NO_CACHE
see naaman '\-\-no\-cache' for information
.TP
NO_SUDO
see naaman '\-\-no\-sudo' for information
.TP
NO_VCS
see naaman '\-\-no\-vcs' for information
.TP
PACMAN
see naaman '\-\-pacman' for information
.TP
REMOVAL
pacman \fB\-R\fR removal options. These entries are passed
.TP
REORDER_DEPS
see naaman '\-\-reorder\-deps' for information
.TP
RPC_CACHE
see naaman '\-\-rpc\-cache' for information
.TP
SCRIPTS
location of scripts naaman uses to perform various operations.
.TP
SKIP_DEPS
see naaman '\-\-skip\-deps' for information
directly to pacman. this option may be specified multiple times.
.TP
VCS_IGNORE
see naaman '\-\-vcs\-ignore' for information
