.TH SEE "1" "January 2018" "naaman.conf" "User Commands"
.SH NAME
see \- naaman.conf
.SH DESCRIPTION
naaman configuration file key information
.SS "options:"
.TP
VCS_IGNORE
see naaman '\-\-vcs\-ignore' for information
.TP
PACMAN
see naaman '\-\-pacman' for information
.TP
NO_VCS
see naaman '\-\-no\-vcs' for information
.TP
NO_SUDO
see naaman '\-\-no\-sudo' for information
.TP
SKIP_DEPS
see naaman '\-\-skip\-deps' for information
.TP
NO_CACHE
see naaman '\-\-no\-cache' for information
.TP
REORDER_DEPS
see naaman '\-\-reorder\-deps' for information
.TP
RPC_CACHE
see naaman '\-\-rpc\-cache' for information
.TP
SCRIPTS
location of scripts used by naaman during operation
.TP
REMOVAL
pacman \fB\-R\fR removal options (addititve)
.TP
MAKEPKG
makepkg options to pass to makepkg (additive)
.TP
IGNORE
see naaman '\-\-ignore' for information
.TP
IGNORE_FOR
see naaman '\-\-ignore-for' for information
